### ISSUE TITLE
Test AJAX call

### ISSUE THREAD

**Issue by nichtich** [programmfabrik/easydb-custom-data-type-gnd#3]
See http://tutorials.jumpstartlab.com/projects/javascript/testing/2-ajax-and-sinon.html for how to mock an HTTP request for testing.

**Comment by StiftungAusNachlass** [comment]
Ich sehe da keine Notwendigkeit für und verstehe auch nicht so ganz, was sinon will.. Wir nutzen die easydb-methode für die Ajax-Calls. Da ist alles notwendige drin. :-)
