### ISSUE TITLE
Speichern und Update von Verweisformen etc. zum Indexieren

### ISSUE THREAD

**Issue by StiftungAusNachlass** [programmfabrik/easydb-custom-data-type-gnd#4]
Aus mehreren Quellen kam die Bitte, dass Verweisformen und evt. auch weitere Angaben zum GND-Eintrag mit in die easydb übernommen werden sollen, damit diese durchsuchbar / findbar sind.

Problem ist: Wie werden diese Daten bei Änderung im Master (DNB) aktualisiert? Ich halte das für nicht machbar / Aufwand größer als Nutzen.

Trotzdem: Vielleicht Einbau von optionaler Möglichkeit Fulltext mit zu übernehmen (Schema-Option)?!

**Comment by nichtich** [comment]
Mir ist noch nicht ganz klar, wie Datenfelder im Plugin auf Datenfelder in der easydb gemappt werden. Momentan habe wir zwei String-Typen `conceptURI` und `conceptName`, in `CustomDataTypeGND.config.yml` tauchen sie aber nicht auf (?)

Generall (auch für andere Normdaten) sollten ein URI-Feld (`conceptURI`) und ein Name-Feld (für die Anzeige) Pflicht sein, allerdings könnte der Name auch aus mehreren Strings für mehrere Sprachen bestehen, wo kann das auf easyDB gemappt werden? Generell können zusätzliche Felder ja unterschiedliche Datentypen haben und ggf. wiederholbar sein, das müsste berücksichtigt werden.

Was das Update betrifft sehe ich das weniger als Problem, so häufig werden einzelne GND-Sätze nicht aktualisiert.

**Comment by lmaylein** [comment]
Ein Update sollte m.E. auf alle Fälle angestrebt werden. Das ist doch u.a. Sinn und Zweck einer Normdateianbindung.

**Comment by StiftungAusNachlass** [comment]
Alle Custom-Data-Type-Plugins haben momentan die Datenfelder "conceptURI" und "conceptName". Es werden jeweils nur die Hauptansetzungsform und die URI des verlinkten Datensatzes gespeichert. Das gilt für GND, GVK, geonames und alle anderen. 

Ich könnte mir vorstellen ein Feld "conceptFulltext" o.ä. einzuführen, in welches einfach alle anderen verfügbaren Informationen zum Normdatensatz geladen werden können. Diese sind dann eben per Volltextsuche oder in der erweiterten Suche findbar. Dann würde auch eine Suche nach "Duero 1471" zum richtigen Albrecht Dürer führen, was sie momentan nicht tut.

Das Feld sollte dann auch gar nicht beim Wählen des Normdatensatzes über das Plugin gefüllt werden, sondern könnte über das noch hypothetische Update-Script befüllt werden. Dann müsste das Befüllen nicht an zwei Stellen implementiert werden.

**Comment by StiftungAusNachlass** [comment]
Updater implementiert in https://github.com/programmfabrik/easydb-custom-data-type-gnd/commit/fd78d2e7df8acb0476957e9e6002d1ef36028cf7
