### ISSUE TITLE
Speichern eines weiteren Datenfeldes "timestamp"

### ISSUE THREAD

**Issue by StiftungAusNachlass** [programmfabrik/easydb-custom-data-type-gnd#5]
Es wurde vorgeschlagen bei jedem Eintragen einer GND-Verknüpfung einen aktuellen timestamp mit zu speichern für eventuelle Updates eventuell mitgespeicherter Synonyme etc..

**Comment by StiftungAusNachlass** [comment]
Ich halte das nicht für sinnvoll, weil es nichts bringt:
1. speichert die easydb sowieso jede Änderung mit timestamp und user in der Änderungshistorie
2. sind die angedachten Updates meiner Meinung nach zwar wünschenswert, werden aber nicht so umgesetzt werden, dass sie vollautomatisiert in verschiedenen Instanzen funktionieren. Insofern ist das Quatsch.

**Comment by nichtich** [comment]
Bevor #4 nicht zumindest im Ansatz umgesetzt ist, brauchen wir uns um Verbesserung eines Update-Verfahrens keine Gedanken zu machen.

**Comment by StiftungAusNachlass** [comment]
Nicht mehr benötigt, CustomUpdater sowohl von programmfabrik als auch hier im Plugin implementiert.
