### ISSUE TITLE
Detailanzeige GND-Schlagwort

### ISSUE THREAD

**Issue by lmaylein** [programmfabrik/easydb-custom-data-type-gnd#6]
Die Ausgabe der GND-URL in der Detailanzeige (nach
der Ansetzungsform in Klammern) ist eher störend.
Lässt sich das optional ausblenden?
Besser wäre ein i-Knopf oder ein Mouseover
ähnlich wie bei der Schlagwortvergabe, über den/das
man sich die weiteren Informationen in einem
Popup einblenden kann.

**Comment by StiftungAusNachlass** [comment]
Die URI wird nicht in Klammern mehr ausgegeben. Stattdessen ist die Ansetzungsform nun ein klickbarer Weblink zur URI.
