### ISSUE TITLE
Weitere GND-Felder?

### ISSUE THREAD

**Issue by lmaylein** [programmfabrik/easydb-custom-data-type-gnd#7]
Hallo, welche GND-Informationen werden denn aktuell über dieses Modul in der easydb abgelegt?
Grund meiner Nachfrage: Orte in der Ansetzungsform gibt es nach RDA wohl nur noch, wenn dieser zur Unterscheidung notwendig ist.
Hier findet sich der Ort nur noch im Feld "Ortsangabe": http://d-nb.info/gnd/1006837-5

Für die Anzeige/Suche in der easydb wäre die Angabe "Paris" durchaus wichtig.
Auf für einen Export spielt das eine Rolle, um z.B. in LIDO nicht nur repositoryName sondern auch repositoryLocation bestücken zu können:

```
<lido:repositoryWrap/>
   <lido:repositorySet/>
         <repositoryName/>
               <lido:legalBodyID @source="GND">http://d-nb.info/gnd/1006837-5
                <lido:legalBodyName>
                        <lido:appellationValue/>Musée du Louvre
<lido:repositoryLocation>
     <lido:placeID/>http://d-nb.info/gnd/4044660-8
       <lido:namePlaceSet>
              <lido:appellationValue>Paris
```

**Comment by StiftungAusNachlass** [comment]
Es werden zur Zeit nur die Hauptansetzungsform und die URI gespeichert.
Wie hier https://github.com/programmfabrik/easydb-custom-data-type-gnd/issues/4#issuecomment-344994143 beschrieben, ist es wahrscheinlich sinnvoll z.B. "Paris" mit in den Volltext aufzunehmen. Dann wäre es findbar.

Für die Nutzung von einzelnen Werten aus Normdaten im easydb-Export müsste man ja alle Normdatenfelder granular in die easydb übernehmen. Das wird mittelfristig für keine Normdatei passieren (ständige Formatanpassungen, Komplexität etc.)

**Comment by KlausThornProgrammfabrik** [comment]
Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.
