### ISSUE TITLE
Tooltip for places

### ISSUE THREAD

**Issue by StiftungAusNachlass** [programmfabrik/easydb-custom-data-type-gnd#8]
Entityfacts now also offers places. With coordinates. Integrate this into the function "__getAdditionalTooltipInfo"...

**Comment by StiftungAusNachlass** [comment]
Example: http://hub.culturegraph.org/entityfacts/4005728-8

**Comment by KlausThornProgrammfabrik** [comment]
Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.
