### ISSUE TITLE
CSV-Import

### ISSUE THREAD

**Issue by m-art-in** [programmfabrik/easydb-custom-data-type-gnd#9]
in EasyDB 5 aktzeptiert der CSV-Importer kein Mapping eines Feldes mit GND-ID auf das entsprechende easyDB-Feld. Denke das ist ein Bug im CSV-Importer.
Oder wie lassen sich massenhaft Datensaätze mit GND-ID importieren?

**Comment by StiftungAusNachlass** [comment]
Das beschriebene Verhalten ist kein Bug, sondern ein fehlendes Feature. Die Unterstützung des CSV-Imports muss bei CustomDataType-Plugins implementiert werden, was bei diesem Plugin noch nicht geschehen ist.

**Comment by m-art-in** [comment]
Ist das auf der Roadmap? Wann ist mit einem Release zu rechnen?

**Comment by StiftungAusNachlass** [comment]
Wir (Verbundzentrale des GBV (VZG)) haben das im Moment mangels Zeit relativ weit unten auf der Liste..

**Comment by KlausThornProgrammfabrik** [comment]
Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.
